### ISSUE TITLE
naming favorites

### ISSUE THREAD

**Issue by cmountvpr** [digitalhappens/MyLittleTools#3]
When added to the list, each favorite comes with its own name. Some of them are easy to interpret, others not so. For example, Lindenberg's Woldemar oscillator is just called "VCO" when added to your module. VCV's dual VCA is just called "VCA". Is it possible to allow the user to rename each favorite? It'd make your already useful utility even better! :)
![Screen Shot 2019-07-12 at 5 46 02 PM](https://user-images.githubusercontent.com/34426574/61160302-f60f6b00-a4cc-11e9-9fd9-7e5904325541.png)

**Comment by deadnoize** [comment]
Thank you for your suggestion, I will integrate such feature in a future version of MyLittleFavorites...

**Comment by digitalhappens** [comment]
Thank you for your suggestion, I will integrate such feature in a future version of MyLittleFavorites...

**Comment by cmountvpr** [comment]
Me again, I have another question. Is it possible to clear an entry in the module?

**Comment by digitalhappens** [comment]
This option will be released in the next version of MyLittleTools...

**Comment by digitalhappens** [comment]
Feature is implemented, and will be released in version 1.0.2 which is by the way very soon.
