### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by patman023** [digitalhappens/MyLittleTools#4]
per readme.md: "This plugin is released under the totally free Public License."

(which btw i've never heard of... maybe you mean public domain?)

per License.txt though, you're releasing under the MIT License.

**Comment by digitalhappens** [comment]
I will try to correct this in the next version... Licensing is a little bit confusing for me, because I am "just" developing... I have to use a license from "https://spdx.org/licenses/"...

**Comment by digitalhappens** [comment]
corrected the readme.md
