### ISSUE TITLE
Banks

### ISSUE THREAD

**Issue by ContemporaryInsanity** [digitalhappens/MyLittleTools#5]
Would it be possible to have banks selected by a knob?  Several people now have a number of MyLittleFavourites in their template patch, if we could have user nameable banks then we could get by with one instance.

**Comment by digitalhappens** [comment]
The next version (1.0.2) is almost ready and contains a super-fast preset loading method, for switching between favorite-lists in one instance.. so stay tuned. Also it features state-saving, it saves the parameter and data-settings per default.
