### ISSUE TITLE
Plugin not installing

### ISSUE THREAD

**Issue by midiguru** [digitalhappens/MyLittleTools#7]
I just updated Rack to 1.1.4, and now the Library menu repeatedly indicates that MyLittleTools 1.0.2 needs to download and update. The folder is in my Rack plugins-v1 folder, and downloaded just now, but it's not installing, and MyLittleTools does not show up in the list of developers in the Browser.

**Comment by matthieuroche** [comment]
Same here. MacOs 10.14.5, vcv 1.1.4, Macbook pro 2015

**Comment by mocmichal** [comment]
same here - win 8.1 Pro. VCV 1.1.4  and MyLittleTools 1.0.2

**Comment by wiqid** [comment]
see also https://github.com/VCVRack/Rack/issues/1534

**Comment by Nightquaker** [comment]
Yep, same here. Just updated to Rack 1.1.4 and MyLittleTools isn't updating properly now.

**Comment by mikeloveridge** [comment]
This is from my Rack log:
[0.111 warn src/plugin.cpp:160] Could not load plugin /home/synth/Music/Rack/plugins-v1/MyLittleTools: Failed to load library /home/synth/Music/Rack/plugins-v1/MyLittleTools/plugin.so: /home/synth/Music/Rack/plugins-v1/MyLittleTools/plugin.so: undefined symbol: _ZN4rack6plugin11allowedTagsB5cxx11E

**Comment by digitalhappens** [comment]
at this time I am on vacation, I will fix this issue as soon as I get back... please have a little patience...

**Comment by digitalhappens** [comment]
a new version of Rack introduced a new tag-structure which affected MyLittleTags, it's corrected
(also it for displaying MyLittleTags chooses the smallest in size tag-alias like "LFO" instead of "Low-frequency oscillator")

it's updated and in the process for rerelease... so wait for MyLittleTools 1.0.3
